# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'cms_pages', '0011_scheduleheaderparagraph'), (b'cms_pages', '0012_auto_20160918_0141')]

    dependencies = [
        ('cms_pages', '0010_auto_20160916_0729'),
        ('symposion_schedule', '0002_presentation_unpublish'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleHeaderParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='header_paragraph', to='symposion_schedule.Schedule')),
            ],
        ),
    ]
