# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0011_scheduleheaderparagraph_squashed_0012_auto_20160918_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamedHeaderParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pass this name to header_paragraph tag.', max_length=64)),
                ('text', models.TextField()),
            ],
        ),
    ]
