# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-18 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [(b'cms_pages', '0015_auto_20160918_0402'), (b'cms_pages', '0016_auto_20160918_0403')]

    dependencies = [
        ('cms_pages', '0014_auto_20160918_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='newsindexpage',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='portrait_image',
        ),
        migrations.RenameField(
            model_name='contentpage',
            old_name='background_image_CUSTOM',
            new_name='background_image',
        ),
        migrations.RenameField(
            model_name='newsindexpage',
            old_name='background_image_CUSTOM',
            new_name='background_image',
        ),
        migrations.RenameField(
            model_name='newspage',
            old_name='background_image_CUSTOM',
            new_name='background_image',
        ),
        migrations.RenameField(
            model_name='newspage',
            old_name='portrait_image_CUSTOM',
            new_name='portrait_image',
        ),
    ]
