# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-17 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_pages', '0020_auto_20170217_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='newsindexpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
