# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_miniconfproposal_tutorialproposal'),
        ('proposals', '0002_auto_20160620_2350'),
    ]

    operations = [
    ]
