# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_auto_20160925_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='kernelproposal',
            name='materials_release',
            field=models.BooleanField(default=True, help_text=b"I allow Linux Australia to release any other material (such as slides) from presentations covered by this proposal, under the <a href='https://creativecommons.org/licenses/by-sa/3.0/au/deed.en'> Creative Commons Attribution-Share Alike Australia 3.0 Licence</a>"),
        ),
        migrations.AddField(
            model_name='kernelproposal',
            name='recording_release',
            field=models.BooleanField(default=True, help_text=b"I allow Linux Australia to release any recordings of presentations covered by this proposal, under the <a href='https://creativecommons.org/licenses/by-sa/3.0/au/deed.en'> Creative Commons Attribution-Share Alike Australia 3.0 Licence</a>"),
        ),
        migrations.AddField(
            model_name='kernelproposal',
            name='target_audience',
            field=models.IntegerField(choices=[(1, b'User'), (2, b'Business'), (3, b'Community'), (4, b'Developer')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='materials_release',
            field=models.BooleanField(default=True, help_text=b"I allow Linux Australia to release any other material (such as slides) from presentations covered by this proposal, under the <a href='https://creativecommons.org/licenses/by-sa/3.0/au/deed.en'> Creative Commons Attribution-Share Alike Australia 3.0 Licence</a>"),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='recording_release',
            field=models.BooleanField(default=True, help_text=b"I allow Linux Australia to release any recordings of presentations covered by this proposal, under the <a href='https://creativecommons.org/licenses/by-sa/3.0/au/deed.en'> Creative Commons Attribution-Share Alike Australia 3.0 Licence</a>"),
        ),
        migrations.AddField(
            model_name='securityproposal',
            name='target_audience',
            field=models.IntegerField(choices=[(1, b'User'), (2, b'Business'), (3, b'Community'), (4, b'Developer')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wootconfproposal',
            name='materials_release',
            field=models.BooleanField(default=True, help_text=b"I allow Linux Australia to release any other material (such as slides) from presentations covered by this proposal, under the <a href='https://creativecommons.org/licenses/by-sa/3.0/au/deed.en'> Creative Commons Attribution-Share Alike Australia 3.0 Licence</a>"),
        ),
        migrations.AddField(
            model_name='wootconfproposal',
            name='recording_release',
            field=models.BooleanField(default=True, help_text=b"I allow Linux Australia to release any recordings of presentations covered by this proposal, under the <a href='https://creativecommons.org/licenses/by-sa/3.0/au/deed.en'> Creative Commons Attribution-Share Alike Australia 3.0 Licence</a>"),
        ),
        migrations.AddField(
            model_name='wootconfproposal',
            name='target_audience',
            field=models.IntegerField(choices=[(1, b'User'), (2, b'Business'), (3, b'Community'), (4, b'Developer')], default=1),
            preserve_default=False,
        ),
    ]
