# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-13 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_pyconauproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyconauproposal',
            name='agreement',
            field=models.BooleanField(default=False, help_text=b'I agree to abide by our <a href="///cms/Terms_Conditions">terms and conditions of attendance</a>, and that all parts of my presentation will adhere to our <a href="///cms/CoC">Code of Conduct</a> '),
        ),
    ]
