# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-15 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0011_pyconauproposal_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyconauproposal',
            name='area',
            field=models.ManyToManyField(help_text=b'Please select the areas of the conference that you think your talk is applicable to. Allowing us to place your talk in any track will give the greatest likelihood of your talk being accepted and also allows us to design the best possible program schedule. The paper committee may ask you to reconsider your desired areas.', to='symposion_conference.Section'),
        ),
    ]
