# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-15 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0012_auto_20170315_2142'),
        ('proposals', '0012_auto_20170315_2112'),
    ]

    operations = [
    ]
