# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinaxcon_registrasion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeeprofile',
            name='accessibility_requirements',
            field=models.CharField(blank=True, max_length=256, verbose_name=b'Accessibility-related requirements'),
        ),
        migrations.AlterField(
            model_name='attendeeprofile',
            name='dietary_restrictions',
            field=models.CharField(blank=True, max_length=256, verbose_name=b'Food allergies, intolerances, or dietary restrictions'),
        ),
    ]
