# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinaxcon_registrasion', '0002_auto_20160922_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendeeprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='attendeeprofile',
            name='address_line_1',
            field=models.CharField(blank=True, help_text=b'This address, if provided, will appear on your invoices.', max_length=1024, verbose_name=b'Address line 1'),
        ),
        migrations.AddField(
            model_name='attendeeprofile',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=1024, verbose_name=b'Address line 2'),
        ),
        migrations.AddField(
            model_name='attendeeprofile',
            name='address_postcode',
            field=models.CharField(blank=True, max_length=1024, verbose_name=b'Postal/Zip code'),
        ),
        migrations.AddField(
            model_name='attendeeprofile',
            name='address_suburb',
            field=models.CharField(blank=True, max_length=1024, verbose_name=b'City/Town/Suburb'),
        ),
        migrations.AlterField(
            model_name='attendeeprofile',
            name='state',
            field=models.CharField(blank=True, max_length=256, verbose_name=b'State/Territory/Province'),
        ),
    ]
