# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 01:33
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pinaxcon_registrasion', '0003_auto_20160922_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeeprofile',
            name='country',
            field=django_countries.fields.CountryField(default=b'AU', max_length=2),
        ),
    ]
